name: Rust formatting check
on:
  pull_request:
    branches: ["*"]
    paths:
      - "**/*.rs"
permissions:
  contents: read
  pull-requests: write
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: dtolnay/rust-toolchain@be39649afda95dbf70f87cce95f68b8d5797b296 # nightly
        with:
          components: rustfmt

      - name: Run rustfmt check
        id: fmt
        run: cargo fmt --all --manifest-path Cargo.toml --check
