name: Nix

on:
  push:
    branches:
      - master
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/nix.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/nix.yml'

permissions: {}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Checkout flake
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@07b8bcba1b22d847db7ee507180c33e115499665 # v8

      - name: Setup magic-nix-cache
        uses: DeterminateSystems/magic-nix-cache-action@55718cd9ebf1737a061487d5ada21abf31e99a98 # main

      - name: Build screenly-cli
        run: nix build .#screenly-cli
